services:
  auth-service:
    build: ./services/auth-service
    volumes:
      - ./services/auth-service:/app
    environment:
      USER_API: http://user-service:8004/user/
      DB_HOST: database-service
    env_file:
        - ./services/auth-service/.env
    ports:
      - 8000:8000

  cart-service:
    build: ./services/cart-service
    volumes:
      - ./services/cart-service:/app
    environment:
      DB_HOST: database-service
    env_file:
        - ./services/cart-service/.env
    ports:
      - 8001:8001

  media-service:
    build: ./services/media-service
    volumes:
      - ./services/media-service:/app
    ports:
      - 8002:8002

  product-service:
    build: ./services/product-service
    volumes:
      - ./services/product-service:/app
    environment:
      DB_HOST: database-service
    env_file:
        - ./services/product-service/.env
    ports:
      - 8003:8003

  user-service:
    build: ./services/user-service
    volumes:
      - ./services/user-service:/app
    environment:
      AUTH_API: http://auth-service:8000/
      DB_HOST: database-service
    env_file:
        - ./services/user-service/.env
    ports:
      - 8004:8004

  database-service:
      build: ./services/database-service
      volumes:
        - ./services/database-service/db_data:/var/lib/postgresql/data
      env_file:
        - ./services/database-service/.env
      ports:
        - 5432:5432

networks:
  flower-network:
    driver: bridge