services:

  auth-service:
    build: ./services/auth-service
    volumes:
      - ./services/auth-service:/app
    network_mode: host

  cart-service:
    build: ./services/cart-service
    volumes:
      - ./services/cart-service:/app
    network_mode: host

  media-service:
    build: ./services/media-service
    volumes:
      - ./services/media-service:/app
    network_mode: host

  product-service:
    build: ./services/product-service
    volumes:
      - ./services/product-service:/app
    network_mode: host

  user-service:
    build: ./services/user-service
    volumes:
      - ./services/user-service:/app
    network_mode: host